main_server:server_json.cpp
	g++ -g -o main_server server_json.cpp -ljson -I/home/yuandong/Downloads/jsoncpp-src-0.5.0/include

main_client:client_json.cpp
	g++ -g -o main_client client_json.cpp -ljson -I/home/yuandong/Downloads/jsoncpp-src-0.5.0/include
