main.exe:bubble.o select.o insert.o heap.o quick.o main.o print.o
	gcc -o main.exe bubble.o select.o insert.o heap.o quick.o main.o print.o
main.o:main.c
	gcc -c main.c
bubble.o:bubble.c
	gcc -c bubble.c
select.o:select.c
	gcc -c select.c
insert.o:insert.c
	gcc -c insert.c
heap.o:heap.c
	gcc -c heap.c
quick.o:quick.c
	gcc -c quick.c
print.o:print.c
	gcc -c print.c
